(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "29^3 + 11^3 = %d\0A\00")
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $a i32)
    (local $b i32)
    (local $c i32)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $a (i32.const 29))
    (local.set $b (i32.const 11))
    (local.set $c (i32.add (i32.mul (i32.mul (local.get $a) (local.get $a)) (local.get $a)) (i32.mul (i32.mul (local.get $b) (local.get $b)) (local.get $b))))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $c)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0)))
