(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "Tried to grow memory by %d pages, in fact it grew by ... %d pages\0A\00")
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $increase_by i32)
    (local $initial_size i32)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $increase_by (i32.const 57))
    (local.set $initial_size (memory.size))
    (drop (memory.grow (local.get $increase_by)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $increase_by)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (memory.size) (local.get $initial_size))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0)))
