(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $seed (mut i32) (i32.const 57))
  (global $__last_offset (mut i32) (i32.const 1061))
  (global $__available_size (mut i32) (i32.const -1))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "%s%.6f\00\00\0A\00, \00min(%d) * \E2\88\9A%d = %.6f\0A\00")
  (func $mulberry32 (result f64)
    (local $t i32)
    (global.set $seed (i32.add (global.get $seed) (i32.const 1831565813)))
    (local.set $t (global.get $seed))
    (local.set $t (i32.mul (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 15))) (i32.or (local.get $t) (i32.const 1))))
    (local.set $t (i32.xor (local.get $t) (i32.add (local.get $t) (i32.mul (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 7))) (i32.or (local.get $t) (i32.const 61))))))
    (f64.div (f64.convert_i32_u (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 14)))) (f64.const 4.294967296E9)))
  (func $array_min_ (param $arr i32) (param $a i32) (param $b i32) (result f64)
    (local $c i32)
    (if (i32.eq (local.get $b) (local.get $a))
      (then
        (return (f64.load align=8 (i32.add (local.get $arr) (i32.mul (local.get $a) (i32.const 8))))))
      (else
        (if (i32.eq (local.get $b) (i32.add (local.get $a) (i32.const 1)))
          (then
            (return (f64.min (f64.load align=8 (i32.add (local.get $arr) (i32.mul (local.get $a) (i32.const 8)))) (f64.load align=8 (i32.add (local.get $arr) (i32.mul (local.get $b) (i32.const 8)))))))
          (else
            (local.set $c (i32.div_s (i32.add (local.get $a) (local.get $b)) (i32.const 2)))
            (return (f64.min (call $array_min_ (local.get $arr) (local.get $a) (local.get $c)) (call $array_min_ (local.get $arr) (i32.add (local.get $c) (i32.const 1)) (local.get $b))))))))
    (unreachable))
  (func $array_min (param $arr i32) (param $N i32) (result f64)
    (call $array_min_ (local.get $arr) (i32.const 0) (i32.sub (local.get $N) (i32.const 1))))
  (func $make_array (param $N i32) (result i32)
    (local $arr i32)
    (local $i i32)
    (local.set $arr (call $malloc (i32.mul (local.get $N) (i32.const 8))))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $i) (local.get $N)))
        (f64.store align=8 (i32.add (local.get $arr) (i32.mul (local.get $i) (i32.const 8))) (call $mulberry32))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_1_continue)))
    (local.get $arr))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $i i32)
    (local $arr i32)
    (local.set $@stack_entry (global.get $@stack))
    (block $@block_1_break
      (local.set $i (i32.const 0))
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $i) (i32.const 100)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (select (i32.const 1031) (select (i32.const 1032) (i32.const 1034) (i32.eqz (i32.rem_s (local.get $i) (i32.const 10)))) (i32.eqz (local.get $i)))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (f64.store align=8 (global.get $@stack) (call $mulberry32))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (i32.const 1024) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_1_continue)))
    (call $printf (i32.const 1032) (global.get $@stack))
    (drop (memory.grow (i32.const 2)))
    (local.set $arr (call $make_array (i32.const 10000)))
    (block $@block_2_break
      (local.set $i (i32.const 1000))
      (loop $@block_2_continue
        (br_if $@block_2_break (i32.gt_s (local.get $i) (i32.const 10000)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $i)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $i)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (f64.store align=8 (global.get $@stack) (f64.mul (f64.sqrt (f64.convert_i32_s (local.get $i))) (call $array_min (local.get $arr) (local.get $i))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
        (call $printf (i32.const 1037) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1000)))
        (br $@block_2_continue)))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0))
  (func $malloc (param $size i32) (result i32)
    (local $res i32)
    (local $pages i32)
    (if (i32.lt_s (global.get $__available_size) (i32.const 0))
      (then
        (global.set $__available_size (i32.mul (i32.const 64000) (memory.size)))))
    (global.set $__last_offset (i32.add (i32.mul (i32.div_s (i32.sub (global.get $__last_offset) (i32.const 1)) (i32.const 8)) (i32.const 8)) (i32.const 8)))
    (local.set $res (global.get $__last_offset))
    (global.set $__last_offset (i32.add (global.get $__last_offset) (local.get $size)))
    (if (i32.gt_s (global.get $__last_offset) (global.get $__available_size))
      (then
        (local.set $pages (i32.add (i32.const 1) (i32.div_s (global.get $__last_offset) (i32.const 64000))))
        (drop (memory.grow (i32.sub (local.get $pages) (memory.size))))
        (global.set $__available_size (i32.mul (i32.const 64000) (local.get $pages)))))
    (local.get $res)))
