(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "x = %d, left = %d, right = %d\0A\00x = %ld, left = %d, right = %d\0A\00%d, %d, %d, %d\0A\00[signed:32] v = %d, w = %d, min = %d, max = %d\0A\00[unsigned:32] v = %u, w = %u, min = %u, max = %u\0A\00[signed:64] r = %ld, s = %ld, min = %ld, max = %ld\0A\00[unsigned:64] r = %lu, s = %lu, min = %lu, max = %lu\0A\00")
  (func $test_int (param $x i32)
    (local $@stack_entry i32)
    (local.set $@stack_entry (global.get $@stack))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $x)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.clz (local.get $x))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.ctz (local.get $x))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry)))
  (func $test_long (param $x i64)
    (local $@stack_entry i32)
    (local.set $@stack_entry (global.get $@stack))
    (i64.store align=8 (global.get $@stack) (local.get $x))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.clz (local.get $x)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.ctz (local.get $x)))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
    (call $printf (i32.const 1055) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry)))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $a i32)
    (local $b i32)
    (local $c i32)
    (local $v i32)
    (local $w i32)
    (local $uv i32)
    (local $uw i32)
    (local $A i64)
    (local $B i64)
    (local $C i64)
    (local $x i64)
    (local $y i64)
    (local $z i64)
    (local $r i64)
    (local $s i64)
    (local $ur i64)
    (local $us i64)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $a (i32.const 1024))
    (local.set $b (i32.const 1048576))
    (local.set $c (i32.const 1073741824))
    (call $test_int (i32.const 0))
    (call $test_int (local.get $a))
    (call $test_int (local.get $b))
    (call $test_int (local.get $c))
    (call $test_int (i32.or (local.get $a) (local.get $b)))
    (call $test_int (i32.or (local.get $a) (local.get $c)))
    (call $test_int (i32.or (local.get $b) (local.get $c)))
    (call $test_int (i32.or (i32.or (local.get $a) (local.get $b)) (local.get $c)))
    (local.set $A (i64.const 1048576))
    (local.set $B (i64.const 1099511627776))
    (local.set $C (i64.const 1152921504606846976))
    (call $test_long (i64.const 0))
    (call $test_long (local.get $A))
    (call $test_long (local.get $B))
    (call $test_long (local.get $C))
    (call $test_long (i64.or (local.get $A) (local.get $B)))
    (call $test_long (i64.or (local.get $A) (local.get $C)))
    (call $test_long (i64.or (local.get $B) (local.get $C)))
    (call $test_long (i64.or (i64.or (local.get $A) (local.get $B)) (local.get $C)))
    (local.set $x (i64.const -9223372036854775808))
    (local.set $y (i64.const 63))
    (local.set $z (i64.shl (i64.const 1) (local.get $y)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.clz (local.get $x)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.ctz (local.get $x)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.clz (local.get $z)))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.wrap_i64 (i64.ctz (local.get $z)))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
    (call $printf (i32.const 1087) (global.get $@stack))
    (local.set $v (i32.const 1073741824))
    (local.set $w (i32.const -2147483648))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $v)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $w)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (call $__min_32s (local.get $v) (local.get $w))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (call $__max_32s (local.get $v) (local.get $w))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
    (call $printf (i32.const 1103) (global.get $@stack))
    (local.set $uv (i32.const 1073741824))
    (local.set $uw (i32.const -2147483648))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_u (local.get $uv)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_u (local.get $uw)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_u (call $__min_32u (local.get $uv) (local.get $uw))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_u (call $__max_32u (local.get $uv) (local.get $uw))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
    (call $printf (i32.const 1151) (global.get $@stack))
    (local.set $r (i64.const 4611686018427387904))
    (local.set $s (i64.const -9223372036854775808))
    (i64.store align=8 (global.get $@stack) (local.get $r))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (local.get $s))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (call $__min_64s (local.get $r) (local.get $s)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (call $__max_64s (local.get $r) (local.get $s)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
    (call $printf (i32.const 1201) (global.get $@stack))
    (local.set $ur (i64.const 4611686018427387904))
    (local.set $us (i64.const -9223372036854775808))
    (i64.store align=8 (global.get $@stack) (local.get $ur))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (local.get $us))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (call $__min_64u (local.get $ur) (local.get $us)))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (call $__max_64u (local.get $ur) (local.get $us)))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
    (call $printf (i32.const 1253) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0))
  (func $__max_32s (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (i32.gt_s (local.get $a) (local.get $b))))
  (func $__min_32s (param $a i32) (param $b i32) (result i32)
    (select (local.get $b) (local.get $a) (i32.gt_s (local.get $a) (local.get $b))))
  (func $__max_32u (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (i32.gt_u (local.get $a) (local.get $b))))
  (func $__min_32u (param $a i32) (param $b i32) (result i32)
    (select (local.get $b) (local.get $a) (i32.gt_u (local.get $a) (local.get $b))))
  (func $__max_64s (param $a i64) (param $b i64) (result i64)
    (select (local.get $a) (local.get $b) (i64.gt_s (local.get $a) (local.get $b))))
  (func $__min_64s (param $a i64) (param $b i64) (result i64)
    (select (local.get $b) (local.get $a) (i64.gt_s (local.get $a) (local.get $b))))
  (func $__max_64u (param $a i64) (param $b i64) (result i64)
    (select (local.get $a) (local.get $b) (i64.gt_u (local.get $a) (local.get $b))))
  (func $__min_64u (param $a i64) (param $b i64) (result i64)
    (select (local.get $b) (local.get $a) (i64.gt_u (local.get $a) (local.get $b)))))
