(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $d (mut i32) (i32.const 3))
  (global $@stack (mut i32) (i32.const 8))
  (memory (export "memory") 1)
  (data (i32.const 1024) "x   x%%%d  floor ceil\0A=====================\0A\00%2d  %2d   %2d    %2d\0A\00")
  (func $mod_ceiling (param $x i32) (result i32)
    (select (local.get $x) (select (i32.sub (i32.add (local.get $x) (global.get $d)) (i32.rem_s (local.get $x) (global.get $d))) (i32.sub (local.get $x) (i32.rem_s (local.get $x) (global.get $d))) (i32.gt_s (local.get $x) (i32.const 0))) (i32.eqz (i32.rem_s (local.get $x) (global.get $d)))))
  (func $mod_floor (param $x i32) (result i32)
    (select (local.get $x) (select (i32.sub (local.get $x) (i32.rem_s (local.get $x) (global.get $d))) (i32.sub (i32.sub (local.get $x) (global.get $d)) (i32.rem_s (local.get $x) (global.get $d))) (i32.gt_s (local.get $x) (i32.const 0))) (i32.eqz (i32.rem_s (local.get $x) (global.get $d)))))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $i i32)
    (local.set $@stack_entry (global.get $@stack))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (global.get $d)))
    (call $printf (i32.const 1024) (global.get $@stack))
    (block $@block_1_break
      (local.set $i (i32.const -7))
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.gt_s (local.get $i) (i32.const 7)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $i)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.rem_s (local.get $i) (global.get $d))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (call $mod_ceiling (local.get $i))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (call $mod_floor (local.get $i))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
        (call $printf (i32.const 1069) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_1_continue)))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0)))
