(module
  (import "c4wa" "printf" (func $printf (param i32) (param i32)))
  (global $seed (mut i32) (i32.const 57))
  (global $__mm_inuse (mut i32) (i32.const 0))
  (global $__mm_expand_by (mut i32) (i32.const 10))
  (global $__mm_extra_offset (mut i32) (i32.const -1))
  (global $@stack (mut i32) (i32.const 8))
  (global $__mm_first (mut i32) (i32.const -1))
  (global $__mm_size (mut i32) (i32.const -1))
  (global $mm_freed (mut i32) (i32.const 0))
  (global $__mm_capacity (mut i32) (i32.const 0))
  (global $world (mut i32) (i32.const 0))
  (global $__mm_stat_freed (mut i32) (i32.const 0))
  (global $mm_allocated (mut i32) (i32.const 0))
  (global $__mm_start (mut i32) (i32.const 0))
  (global $__mm_stat_allocated (mut i32) (i32.const 0))
  (memory (export "memory") 1)
  (data (i32.const 1024) "MM: We are at capacity with limit of %d storage units reached\0A\00MM: Need %d more page(s) in addition to currently allocated %d\0A\00MM: Allocating additional map at index %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22__mm_inuse < __mm_capacity\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22__mm_first >= 0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22*cur != 0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22j >= 0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22j < 64\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22box == (void *)cur + 8 + j*__mm_size\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22(*cur & (unsigned long)1 << (unsigned long)j) == 0\22 @ line %d\0A\00A/R/C: %d/%d/%d; CAP: %d/%d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22g->level == w->level - 1\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22g->size == w->size/N\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22g->x0 == w->x0 + g->size * x\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22g->y0 == w->y0 + g->size * y\22 @ line %d\0A\00set_cell(%d, %d, %d)\0A\00Point %d, %d is outside the world %d, %d, %d, %d\0A\00xmin = %d, xmax = %d, ymin = %d, ymax = %d\0A\00Level: %d => %d, Size: %d => %d\0A\00Converged to original box @ %d, %d (size %d)\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22w->x0 + xp*wsize == world->x0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22w->y0 + yp*wsize == world->y0\22 @ line %d\0A\00w->x0 = %d, xp = %d, wsize = %d, w->y0 = %d, yp = %d\0A\00Entering (%d,%d) into <%d,%d,%d,%d>\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22w->x0 <= x && x < w->x0 + w->size && w->y0 <= y && y < w->y0 + w->size\22 @ line %d\0A\00Assigned <%d,%d,%d>[%d] = %d\0A\00Going down to level %d, xp = %d, yp = %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22t1 == w->level\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22t2 == w->x0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22t3 == w->y0\22 @ line %d\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22size == w->size\22 @ line %d\0A\00Done!\0A\00Trying to locate (%d,%d) in <%d,%d,%d,%d>\0A\00Got to the bottom <%d,%d,%d>[%d]\0A\00[<%d,%d,%d>\00 (%d,%d)\00]\00.\00\0A\00\E2\80\BC\EF\B8\8F ASSERTION: \22*k < n\22 @ line %d\0A\00Raw In    :\00\0ASorted In :\00\0ASorted Out:\00\0ARaw Out   :\00\E2\80\BC\EF\B8\8F ASSERTION: \22get_cell(x,y) == mulberry32() < density\22 @ line %d\0A\00OK\0A\00\F0\9F\A7\AA Test %d\0A\00")
  (func $mm_init (param $extra_offset i32) (param $size i32)
    (if (block $@block_1_break (result i32) (drop (br_if $@block_1_break (i32.const 1) (i32.lt_s (local.get $extra_offset) (i32.const 0)))) (drop (br_if $@block_1_break (i32.const 1) (i32.lt_s (local.get $size) (i32.const 1)))) (drop (br_if $@block_1_break (i32.const 1) (global.get $__mm_start))) (i32.const 0))
      (then
        (unreachable)))
    (global.set $__mm_extra_offset (local.get $extra_offset))
    (global.set $__mm_size (i32.add (i32.mul (i32.div_s (i32.sub (local.get $size) (i32.const 1)) (i32.const 8)) (i32.const 8)) (i32.const 8)))
    (if (if (result i32) (i32.eqz (i32.const 1)) (then (i32.const 0)) (else (i32.ne (i32.gt_s (i32.rem_s (i32.add (i32.const 2873) (global.get $__mm_extra_offset)) (i32.const 8)) (i32.const 0)) (i32.const 0))))
      (then
        (global.set $__mm_extra_offset (i32.add (global.get $__mm_extra_offset) (i32.sub (i32.const 8) (i32.rem_s (i32.add (i32.const 2873) (global.get $__mm_extra_offset)) (i32.const 8)))))))
    (global.set $__mm_start (i32.add (i32.const 2873) (global.get $__mm_extra_offset))))
  (func $malloc (param $size i32) (result i32)
    (local $@stack_entry i32)
    (local $verbose i32)
    (local $unit_size i32)
    (local $required i32)
    (local $j i32)
    (local $result i32)
    (local.set $@stack_entry (global.get $@stack))
    (global.set $__mm_stat_allocated (i32.add (global.get $__mm_stat_allocated) (i32.const 1)))
    (if (i32.eqz (global.get $__mm_start))
      (then
        (call $mm_init (i32.const 0) (local.get $size))))
    (if (i32.gt_s (local.get $size) (global.get $__mm_size))
      (then
        (unreachable)))
    (local.set $unit_size (i32.add (i32.const 1) (i32.mul (i32.const 8) (global.get $__mm_size))))
    (if (if (result i32) (i32.ge_s (global.get $__mm_first) (i32.const 0)) (then (i32.const 0)) (else (i32.ne (i32.eq (global.get $__mm_inuse) (global.get $__mm_capacity)) (i32.const 0))))
      (then
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (global.get $__mm_capacity)))
            (call $printf (i32.const 1024) (global.get $@stack))))
        (local.set $required (i32.add (i32.div_s (i32.add (i32.add (i32.const 2873) (global.get $__mm_extra_offset)) (i32.mul (i32.mul (i32.add (global.get $__mm_capacity) (global.get $__mm_expand_by)) (i32.const 8)) (local.get $unit_size))) (i32.const 64000)) (i32.const 1)))
        (if (i32.gt_s (local.get $required) (memory.size))
          (then
            (if (local.get $verbose)
              (then
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (local.get $required) (memory.size))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (memory.size)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (i32.const 1087) (global.get $@stack))))
            (drop (memory.grow (i32.sub (local.get $required) (memory.size))))))
        (global.set $__mm_capacity (i32.add (global.get $__mm_capacity) (global.get $__mm_expand_by)))))
    (if (i32.lt_s (global.get $__mm_first) (i32.const 0))
      (then
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (global.get $__mm_inuse)))
            (call $printf (i32.const 1151) (global.get $@stack))))
        (if (i32.ge_s (global.get $__mm_inuse) (global.get $__mm_capacity))
          (then
            (i64.store align=8 (global.get $@stack) (i64.const 133))
            (call $printf (i32.const 1194) (global.get $@stack))
            (unreachable)))
        (i64.store align=8 (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_inuse) (local.get $unit_size)) (i32.const 8))) (i64.const -1))
        (global.set $__mm_first (global.get $__mm_inuse))
        (global.set $__mm_inuse (i32.add (global.get $__mm_inuse) (i32.const 1)))))
    (if (i32.lt_s (global.get $__mm_first) (i32.const 0))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 139))
        (call $printf (i32.const 1252) (global.get $@stack))
        (unreachable)))
    (local.set $required (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_first) (local.get $unit_size)) (i32.const 8))))
    (if (i64.eq (i64.load align=8 (local.get $required)) (i64.const 0))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 141))
        (call $printf (i32.const 1299) (global.get $@stack))
        (unreachable)))
    (local.set $j (i32.wrap_i64 (i64.ctz (i64.load align=8 (local.get $required)))))
    (i64.store align=8 (local.get $required) (i64.xor (i64.load align=8 (local.get $required)) (i64.shl (i64.const 1) (i64.extend_i32_s (local.get $j)))))
    (local.set $result (i32.add (i32.add (local.get $required) (i32.const 8)) (i32.mul (local.get $j) (global.get $__mm_size))))
    (if (i64.eqz (i64.load align=8 (local.get $required)))
      (then
        (loop $@block_5_1_continue
          (global.set $__mm_first (i32.add (global.get $__mm_first) (i32.const 1)))
          (br_if $@block_5_1_continue (if (result i32) (i32.ge_s (global.get $__mm_first) (global.get $__mm_inuse)) (then (i32.const 0)) (else (i32.ne (i64.eqz (i64.load align=8 (i32.add (global.get $__mm_start) (i32.mul (i32.mul (global.get $__mm_first) (local.get $unit_size)) (i32.const 8))))) (i32.const 0))))))
        (if (i32.eq (global.get $__mm_first) (global.get $__mm_inuse))
          (then
            (global.set $__mm_first (i32.const -1))))))
    (global.set $@stack (local.get $@stack_entry))
    (local.get $result))
  (func $free (param $box i32)
    (local $@stack_entry i32)
    (local $unit_size i32)
    (local $offset i32)
    (local $idx i32)
    (local $cur i32)
    (local $j i32)
    (local.set $@stack_entry (global.get $@stack))
    (global.set $__mm_stat_freed (i32.add (global.get $__mm_stat_freed) (i32.const 1)))
    (local.set $unit_size (i32.add (i32.const 1) (i32.mul (i32.const 8) (global.get $__mm_size))))
    (local.set $offset (i32.sub (local.get $box) (global.get $__mm_start)))
    (local.set $idx (i32.div_s (i32.div_s (local.get $offset) (local.get $unit_size)) (i32.const 8)))
    (local.set $cur (i32.add (global.get $__mm_start) (i32.mul (i32.mul (local.get $idx) (local.get $unit_size)) (i32.const 8))))
    (local.set $j (i32.div_s (i32.sub (i32.sub (local.get $box) (local.get $cur)) (i32.const 8)) (global.get $__mm_size)))
    (if (i32.lt_s (local.get $j) (i32.const 0))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 169))
        (call $printf (i32.const 1340) (global.get $@stack))
        (unreachable)))
    (if (i32.ge_s (local.get $j) (i32.const 64))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 170))
        (call $printf (i32.const 1378) (global.get $@stack))
        (unreachable)))
    (if (i32.ne (local.get $box) (i32.add (i32.add (local.get $cur) (i32.const 8)) (i32.mul (local.get $j) (global.get $__mm_size))))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 171))
        (call $printf (i32.const 1416) (global.get $@stack))
        (unreachable)))
    (if (i32.wrap_i64 (i64.and (i64.load align=8 (local.get $cur)) (i64.shl (i64.const 1) (i64.extend_i32_s (local.get $j)))))
      (then
        (i64.store align=8 (global.get $@stack) (i64.const 172))
        (call $printf (i32.const 1484) (global.get $@stack))
        (unreachable)))
    (i64.store align=8 (local.get $cur) (i64.xor (i64.load align=8 (local.get $cur)) (i64.shl (i64.const 1) (i64.extend_i32_s (local.get $j)))))
    (if (i32.lt_s (local.get $idx) (global.get $__mm_first))
      (then
        (global.set $__mm_first (local.get $idx))))
    (global.set $@stack (local.get $@stack_entry)))
  (func $__mm_count_boxes (result i32)
    (local $unit_size i32)
    (local $res i32)
    (local $i i32)
    (local.set $unit_size (i32.add (i32.const 1) (i32.mul (i32.const 8) (global.get $__mm_size))))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $i) (global.get $__mm_inuse)))
        (local.set $res (i32.add (local.get $res) (i32.sub (i32.const 64) (i32.wrap_i64 (i64.popcnt (i64.load align=8 (i32.add (global.get $__mm_start) (i32.mul (i32.mul (local.get $i) (local.get $unit_size)) (i32.const 8)))))))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_1_continue)))
    (local.get $res))
  (func $mm_stat (param $allocated i32) (param $freed i32) (param $current i32) (param $in_use i32) (param $capacity i32)
    (i32.store align=4 (local.get $allocated) (global.get $__mm_stat_allocated))
    (i32.store align=4 (local.get $freed) (global.get $__mm_stat_freed))
    (i32.store align=4 (local.get $current) (call $__mm_count_boxes))
    (i32.store align=4 (local.get $in_use) (global.get $__mm_inuse))
    (i32.store align=4 (local.get $capacity) (global.get $__mm_capacity)))
  (func $alloc_new_box (param $level i32) (param $x0 i32) (param $y0 i32) (result i32)
    (local $box i32)
    (local $size i32)
    (local $k i32)
    (global.set $mm_allocated (i32.add (global.get $mm_allocated) (i32.const 1)))
    (local.set $box (call $malloc (select (i32.const 216) (i32.const 116) (i32.eqz (local.get $level)))))
    (memory.fill (local.get $box) (i32.const 0) (select (i32.const 216) (i32.const 116) (i32.eqz (local.get $level))))
    (local.set $size (i32.const 10))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $k) (local.get $level)))
        (local.set $size (i32.mul (local.get $size) (i32.const 5)))
        (local.set $k (i32.add (local.get $k) (i32.const 1)))
        (br $@block_1_continue)))
    (i32.store align=4 (local.get $box) (local.get $level))
    (i32.store align=4 (i32.add (local.get $box) (i32.const 4)) (local.get $x0))
    (i32.store align=4 (i32.add (local.get $box) (i32.const 8)) (local.get $y0))
    (i32.store align=4 (i32.add (local.get $box) (i32.const 12)) (local.get $size))
    (local.get $box))
  (func $release_box (param $box i32)
    (local $y i32)
    (local $x i32)
    (global.set $mm_freed (i32.add (global.get $mm_freed) (i32.const 1)))
    (if (i32.gt_s (i32.load align=4 (local.get $box)) (i32.const 0))
      (then
        (block $@block_1_1_break
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $y) (i32.const 5)))
            (block $@block_1_1_1_break
              (local.set $x (i32.const 0))
              (loop $@block_1_1_1_continue
                (br_if $@block_1_1_1_break (i32.ge_s (local.get $x) (i32.const 5)))
                (if (i32.load align=4 (i32.add (i32.add (local.get $box) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4))))
                  (then
                    (call $release_box (i32.load align=4 (i32.add (i32.add (local.get $box) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))))))
                (local.set $x (i32.add (local.get $x) (i32.const 1)))
                (br $@block_1_1_1_continue)))
            (local.set $y (i32.add (local.get $y) (i32.const 1)))
            (br $@block_1_1_continue)))))
    (call $free (local.get $box)))
  (func $memory_stat
    (local $@stack_entry i32)
    (local $allocated i32)
    (local $freed i32)
    (local $current i32)
    (local $in_use i32)
    (local $capacity i32)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $allocated (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (local.set $freed (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (local.set $current (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (local.set $in_use (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (local.set $capacity (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (call $mm_stat (local.get $allocated) (local.get $freed) (local.get $current) (local.get $in_use) (local.get $capacity))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $allocated))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $freed))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $current))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $in_use))))
    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $capacity))))
    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
    (call $printf (i32.const 1566) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry)))
  (func $verify (param $w i32)
    (local $@stack_entry i32)
    (local $y i32)
    (local $x i32)
    (local $g i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (i32.eqz (i32.load align=4 (local.get $w)))
      (then
        (global.set $@stack (local.get $@stack_entry))
        (return)))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (i32.const 5)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (i32.const 5)))
            (local.set $g (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))))
            (if (local.get $g)
              (then
                (if (i32.ne (i32.load align=4 (local.get $g)) (i32.sub (i32.load align=4 (local.get $w)) (i32.const 1)))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 263))
                    (call $printf (i32.const 1595) (global.get $@stack))
                    (unreachable)))
                (if (i32.ne (i32.load align=4 (i32.add (local.get $g) (i32.const 12))) (i32.div_s (i32.load align=4 (i32.add (local.get $w) (i32.const 12))) (i32.const 5)))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 264))
                    (call $printf (i32.const 1651) (global.get $@stack))
                    (unreachable)))
                (if (i32.ne (i32.load align=4 (i32.add (local.get $g) (i32.const 4))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (i32.load align=4 (i32.add (local.get $g) (i32.const 12))) (local.get $x))))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 265))
                    (call $printf (i32.const 1703) (global.get $@stack))
                    (unreachable)))
                (if (i32.ne (i32.load align=4 (i32.add (local.get $g) (i32.const 8))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (i32.load align=4 (i32.add (local.get $g) (i32.const 12))) (local.get $y))))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 266))
                    (call $printf (i32.const 1763) (global.get $@stack))
                    (unreachable)))
                (call $verify (local.get $g))))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue)))
    (global.set $@stack (local.get $@stack_entry)))
  (func $set_cell (param $x i32) (param $y i32) (param $val i32)
    (local $@stack_entry i32)
    (local $w i32)
    (local $t i32)
    (local $xp i32)
    (local $yp i32)
    (local $verbose i32)
    (local $box i32)
    (local $xmin i32)
    (local $ymin i32)
    (local $xmax i32)
    (local $ymax i32)
    (local $new_level i32)
    (local $new_size i32)
    (local $dx i32)
    (local $dy i32)
    (local $new_world i32)
    (local $wsize i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (local.get $verbose)
      (then
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $x)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $y)))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $val)))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
        (call $printf (i32.const 1823) (global.get $@stack))))
    (if (i32.eqz (global.get $world))
      (then
        (if (i32.eqz (local.get $val))
          (then
            (global.set $@stack (local.get $@stack_entry))
            (return)))
        (local.set $box (call $alloc_new_box (i32.const 0) (i32.sub (local.get $x) (i32.const 5)) (i32.sub (local.get $y) (i32.const 5))))
        (i32.store8 align=1 (i32.add (i32.add (local.get $box) (i32.const 16)) (i32.add (i32.mul (i32.const 10) (i32.sub (local.get $y) (i32.load align=4 (i32.add (local.get $box) (i32.const 8))))) (i32.sub (local.get $x) (i32.load align=4 (i32.add (local.get $box) (i32.const 4)))))) (i32.const 1))
        (global.set $world (local.get $box))
        (global.set $@stack (local.get $@stack_entry))
        (return)))
    (local.set $box (i32.load align=4 (i32.add (global.get $world) (i32.const 12))))
    (if (i32.eqz (block $@block_2_break (result i32) (drop (br_if $@block_2_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (global.get $world) (i32.const 4))) (local.get $x)))) (drop (br_if $@block_2_break (i32.const 0) (i32.ge_s (local.get $x) (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 4))) (local.get $box))))) (drop (br_if $@block_2_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (global.get $world) (i32.const 8))) (local.get $y)))) (drop (br_if $@block_2_break (i32.const 0) (i32.ge_s (local.get $y) (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 8))) (local.get $box))))) (i32.const 1)))
      (then
        (if (i32.eqz (local.get $val))
          (then
            (global.set $@stack (local.get $@stack_entry))
            (return)))
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $x)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $y)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (global.get $world) (i32.const 4)))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 4))) (local.get $box)) (i32.const 1))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (global.get $world) (i32.const 8)))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 8))) (local.get $box)) (i32.const 1))))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 40)))
            (call $printf (i32.const 1845) (global.get $@stack))))
        (local.set $xmin (i32.load align=4 (i32.add (global.get $world) (i32.const 4))))
        (if (i32.lt_s (local.get $x) (local.get $xmin))
          (then
            (local.set $t (i32.sub (local.get $xmin) (local.get $x)))
            (if (i32.ne (i32.rem_s (local.get $t) (local.get $box)) (i32.const 0))
              (then
                (local.set $t (i32.add (local.get $t) (i32.sub (local.get $box) (i32.rem_s (local.get $t) (local.get $box)))))))
            (local.set $xmin (i32.sub (local.get $xmin) (local.get $t)))))
        (local.set $ymin (i32.load align=4 (i32.add (global.get $world) (i32.const 8))))
        (if (i32.lt_s (local.get $y) (local.get $ymin))
          (then
            (local.set $t (i32.sub (local.get $ymin) (local.get $y)))
            (if (i32.ne (i32.rem_s (local.get $t) (local.get $box)) (i32.const 0))
              (then
                (local.set $t (i32.add (local.get $t) (i32.sub (local.get $box) (i32.rem_s (local.get $t) (local.get $box)))))))
            (local.set $ymin (i32.sub (local.get $ymin) (local.get $t)))))
        (local.set $xmax (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 4))) (local.get $box)))
        (if (i32.gt_s (i32.add (local.get $x) (i32.const 1)) (local.get $xmax))
          (then
            (local.set $t (i32.sub (i32.add (local.get $x) (i32.const 1)) (local.get $xmax)))
            (if (i32.ne (i32.rem_s (local.get $t) (local.get $box)) (i32.const 0))
              (then
                (local.set $t (i32.add (local.get $t) (i32.sub (local.get $box) (i32.rem_s (local.get $t) (local.get $box)))))))
            (local.set $xmax (i32.add (local.get $xmax) (local.get $t)))))
        (local.set $ymax (i32.add (i32.load align=4 (i32.add (global.get $world) (i32.const 8))) (local.get $box)))
        (if (i32.gt_s (i32.add (local.get $y) (i32.const 1)) (local.get $ymax))
          (then
            (local.set $t (i32.sub (i32.add (local.get $y) (i32.const 1)) (local.get $ymax)))
            (if (i32.ne (i32.rem_s (local.get $t) (local.get $box)) (i32.const 0))
              (then
                (local.set $t (i32.add (local.get $t) (i32.sub (local.get $box) (i32.rem_s (local.get $t) (local.get $box)))))))
            (local.set $ymax (i32.add (local.get $ymax) (local.get $t)))))
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $xmin)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $xmax)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $ymin)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $ymax)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
            (call $printf (i32.const 1895) (global.get $@stack))))
        (local.set $new_level (i32.load align=4 (global.get $world)))
        (local.set $new_size (local.get $box))
        (loop $@block_3_5_continue
          (local.set $new_size (i32.mul (local.get $new_size) (i32.const 5)))
          (local.set $new_level (i32.add (local.get $new_level) (i32.const 1)))
          (br_if $@block_3_5_continue (if (result i32) (i32.lt_s (local.get $new_size) (i32.sub (local.get $xmax) (local.get $xmin))) (then (i32.const 1)) (else (i32.ne (i32.lt_s (local.get $new_size) (i32.sub (local.get $ymax) (local.get $ymin))) (i32.const 0))))))
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (global.get $world))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $new_level)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $box)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $new_size)))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
            (call $printf (i32.const 1939) (global.get $@stack))))
        (local.set $dx (i32.div_s (i32.add (i32.sub (local.get $new_size) (local.get $xmax)) (local.get $xmin)) (i32.const 2)))
        (if (i32.ne (i32.rem_s (local.get $dx) (local.get $box)) (i32.const 0))
          (then
            (local.set $dx (i32.add (local.get $dx) (i32.sub (local.get $box) (i32.rem_s (local.get $dx) (local.get $box)))))))
        (local.set $dy (i32.div_s (i32.add (i32.sub (local.get $new_size) (local.get $ymax)) (local.get $ymin)) (i32.const 2)))
        (if (i32.ne (i32.rem_s (local.get $dy) (local.get $box)) (i32.const 0))
          (then
            (local.set $dy (i32.add (local.get $dy) (i32.sub (local.get $box) (i32.rem_s (local.get $dy) (local.get $box)))))))
        (local.set $new_world (call $alloc_new_box (local.get $new_level) (i32.sub (local.get $xmin) (local.get $dx)) (i32.sub (local.get $ymin) (local.get $dy))))
        (local.set $w (local.get $new_world))
        (local.set $wsize (i32.div_s (local.get $new_size) (i32.const 5)))
        (block $@block_3_6_break
          (loop $@block_3_6_continue
            (local.set $xp (i32.div_s (i32.sub (i32.load align=4 (i32.add (global.get $world) (i32.const 4))) (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))) (local.get $wsize)))
            (local.set $yp (i32.div_s (i32.sub (i32.load align=4 (i32.add (global.get $world) (i32.const 8))) (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))) (local.get $wsize)))
            (if (i32.eq (local.get $wsize) (i32.load align=4 (i32.add (global.get $world) (i32.const 12))))
              (then
                (if (local.get $verbose)
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (local.get $xp) (local.get $wsize)))))
                    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (local.get $yp) (local.get $wsize)))))
                    (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                    (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $wsize)))
                    (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                    (call $printf (i32.const 1972) (global.get $@stack))))
                (if (i32.ne (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (local.get $xp) (local.get $wsize))) (i32.load align=4 (i32.add (global.get $world) (i32.const 4))))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 351))
                    (call $printf (i32.const 2018) (global.get $@stack))
                    (unreachable)))
                (if (i32.ne (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (local.get $yp) (local.get $wsize))) (i32.load align=4 (i32.add (global.get $world) (i32.const 8))))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 352))
                    (call $printf (i32.const 2079) (global.get $@stack))
                    (unreachable)))
                (i32.store align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (i32.const 5) (local.get $yp)) (local.get $xp)) (i32.const 4))) (global.get $world))
                (br $@block_3_6_break)))
            (local.set $new_level (i32.sub (local.get $new_level) (i32.const 1)))
            (if (local.get $verbose)
              (then
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $xp)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $wsize)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $yp)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
                (call $printf (i32.const 2140) (global.get $@stack))))
            (i32.store align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (i32.const 5) (local.get $yp)) (local.get $xp)) (i32.const 4))) (call $alloc_new_box (local.get $new_level) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (local.get $xp) (local.get $wsize))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (local.get $yp) (local.get $wsize)))))
            (local.set $w (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (i32.const 5) (local.get $yp)) (local.get $xp)) (i32.const 4)))))
            (local.set $wsize (i32.div_s (local.get $wsize) (i32.const 5)))
            (br $@block_3_6_continue)))
        (global.set $world (local.get $new_world))))
    (local.set $w (global.get $world))
    (block $@block_4_break
      (loop $@block_4_continue
        (if (local.get $verbose)
          (then
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $x)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $y)))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
            (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
            (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 12)))))
            (global.set $@stack (i32.sub (global.get $@stack) (i32.const 40)))
            (call $printf (i32.const 2194) (global.get $@stack))))
        (if (i32.eqz (block $@block_4_1_break (result i32) (drop (br_if $@block_4_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (local.get $x)))) (drop (br_if $@block_4_1_break (i32.const 0) (i32.ge_s (local.get $x) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (drop (br_if $@block_4_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (local.get $y)))) (drop (br_if $@block_4_1_break (i32.const 0) (i32.ge_s (local.get $y) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (i32.const 1)))
          (then
            (i64.store align=8 (global.get $@stack) (i64.const 372))
            (call $printf (i32.const 2231) (global.get $@stack))
            (unreachable)))
        (if (i32.eqz (i32.load align=4 (local.get $w)))
          (then
            (local.set $xp (i32.sub (local.get $x) (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
            (local.set $yp (i32.sub (local.get $y) (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
            (if (local.get $verbose)
              (then
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.mul (local.get $yp) (i32.const 10)) (local.get $xp))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $val)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 32)))
                (call $printf (i32.const 2333) (global.get $@stack))))
            (i32.store8 align=1 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.add (i32.mul (local.get $yp) (i32.const 10)) (local.get $xp))) (local.get $val))
            (br $@block_4_break))
          (else
            (local.set $box (i32.div_s (i32.load align=4 (i32.add (local.get $w) (i32.const 12))) (i32.const 5)))
            (local.set $xp (i32.div_s (i32.sub (local.get $x) (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))) (local.get $box)))
            (local.set $yp (i32.div_s (i32.sub (local.get $y) (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))) (local.get $box)))
            (if (local.get $verbose)
              (then
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.load align=4 (local.get $w)) (i32.const 1))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $xp)))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $yp)))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
                (call $printf (i32.const 2363) (global.get $@stack))))
            (if (i32.eqz (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $yp) (i32.const 5)) (local.get $xp)) (i32.const 4)))))
              (then
                (if (i32.eqz (local.get $val))
                  (then
                    (global.set $@stack (local.get $@stack_entry))
                    (return)))
                (i32.store align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $yp) (i32.const 5)) (local.get $xp)) (i32.const 4))) (call $alloc_new_box (i32.sub (i32.load align=4 (local.get $w)) (i32.const 1)) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (local.get $xp) (local.get $box))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (local.get $yp) (local.get $box)))))))
            (local.set $xmin (i32.sub (i32.load align=4 (local.get $w)) (i32.const 1)))
            (local.set $ymin (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.mul (local.get $xp) (local.get $box))))
            (local.set $xmax (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.mul (local.get $yp) (local.get $box))))
            (local.set $w (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $yp) (i32.const 5)) (local.get $xp)) (i32.const 4)))))
            (if (i32.ne (local.get $xmin) (i32.load align=4 (local.get $w)))
              (then
                (i64.store align=8 (global.get $@stack) (i64.const 395))
                (call $printf (i32.const 2405) (global.get $@stack))
                (unreachable)))
            (if (i32.ne (local.get $ymin) (i32.load align=4 (i32.add (local.get $w) (i32.const 4))))
              (then
                (i64.store align=8 (global.get $@stack) (i64.const 396))
                (call $printf (i32.const 2451) (global.get $@stack))
                (unreachable)))
            (if (i32.ne (local.get $xmax) (i32.load align=4 (i32.add (local.get $w) (i32.const 8))))
              (then
                (i64.store align=8 (global.get $@stack) (i64.const 397))
                (call $printf (i32.const 2494) (global.get $@stack))
                (unreachable)))
            (if (i32.ne (local.get $box) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))
              (then
                (i64.store align=8 (global.get $@stack) (i64.const 398))
                (call $printf (i32.const 2537) (global.get $@stack))
                (unreachable)))))
        (br $@block_4_continue)))
    (if (local.get $verbose)
      (then
        (call $printf (i32.const 2584) (global.get $@stack))))
    (global.set $@stack (local.get $@stack_entry)))
  (func $get_cell (param $x i32) (param $y i32) (result i32)
    (local $@stack_entry i32)
    (local $verbose i32)
    (local $xp i32)
    (local $yp i32)
    (local $size i32)
    (local $w i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (i32.eqz (global.get $world))
      (then
        (global.set $@stack (local.get $@stack_entry))
        (return (i32.const 0))))
    (local.set $w (global.get $world))
    (if (i32.eqz (block $@block_1_break (result i32) (drop (br_if $@block_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (local.get $x)))) (drop (br_if $@block_1_break (i32.const 0) (i32.ge_s (local.get $x) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (drop (br_if $@block_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (local.get $y)))) (drop (br_if $@block_1_break (i32.const 0) (i32.ge_s (local.get $y) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (i32.const 1)))
      (then
        (global.set $@stack (local.get $@stack_entry))
        (return (i32.const 0))))
    (loop $@block_2_continue
      (if (local.get $verbose)
        (then
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $x)))
          (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $y)))
          (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
          (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
          (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
          (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
          (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 12)))))
          (global.set $@stack (i32.sub (global.get $@stack) (i32.const 40)))
          (call $printf (i32.const 2591) (global.get $@stack))))
      (if (i32.eqz (block $@block_2_1_break (result i32) (drop (br_if $@block_2_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (local.get $x)))) (drop (br_if $@block_2_1_break (i32.const 0) (i32.ge_s (local.get $x) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (drop (br_if $@block_2_1_break (i32.const 0) (i32.gt_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (local.get $y)))) (drop (br_if $@block_2_1_break (i32.const 0) (i32.ge_s (local.get $y) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (i32.load align=4 (i32.add (local.get $w) (i32.const 12))))))) (i32.const 1)))
        (then
          (i64.store align=8 (global.get $@stack) (i64.const 424))
          (call $printf (i32.const 2231) (global.get $@stack))
          (unreachable)))
      (if (i32.eqz (i32.load align=4 (local.get $w)))
        (then
          (local.set $xp (i32.sub (local.get $x) (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
          (local.set $yp (i32.sub (local.get $y) (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
          (if (local.get $verbose)
            (then
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
              (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
              (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
              (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.mul (local.get $yp) (i32.const 10)) (local.get $xp))))
              (global.set $@stack (i32.sub (global.get $@stack) (i32.const 24)))
              (call $printf (i32.const 2634) (global.get $@stack))))
          (global.set $@stack (local.get $@stack_entry))
          (return (i32.load8_s align=1 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.add (i32.mul (local.get $yp) (i32.const 10)) (local.get $xp))))))
        (else
          (local.set $size (i32.div_s (i32.load align=4 (i32.add (local.get $w) (i32.const 12))) (i32.const 5)))
          (local.set $xp (i32.div_s (i32.sub (local.get $x) (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))) (local.get $size)))
          (local.set $yp (i32.div_s (i32.sub (local.get $y) (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))) (local.get $size)))
          (if (local.get $verbose)
            (then
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.sub (i32.load align=4 (local.get $w)) (i32.const 1))))
              (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $xp)))
              (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
              (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $yp)))
              (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
              (call $printf (i32.const 2363) (global.get $@stack))))
          (local.set $w (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $yp) (i32.const 5)) (local.get $xp)) (i32.const 4)))))))
      (br_if $@block_2_continue (local.get $w)))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0))
  (func $dump_cells0 (param $w i32) (param $verbose i32)
    (local $@stack_entry i32)
    (local $y i32)
    (local $x i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (local.get $verbose)
      (then
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
        (call $printf (i32.const 2668) (global.get $@stack))))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (i32.const 10)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (i32.const 10)))
            (if (i32.load8_s align=1 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.add (i32.mul (local.get $y) (i32.const 10)) (local.get $x))))
              (then
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (local.get $x))))
                (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
                (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (local.get $y))))
                (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
                (call $printf (i32.const 2680) (global.get $@stack))))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue)))
    (if (local.get $verbose)
      (then
        (call $printf (i32.const 2689) (global.get $@stack))))
    (global.set $@stack (local.get $@stack_entry)))
  (func $dump_cells (param $w i32) (param $verbose i32)
    (local $@stack_entry i32)
    (local $y i32)
    (local $x i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (local.get $verbose)
      (then
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (local.get $w))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 4)))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $w) (i32.const 8)))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 16)))
        (call $printf (i32.const 2668) (global.get $@stack))))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (i32.const 5)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (i32.const 5)))
            (if (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4))))
              (then
                (if (i32.eq (i32.load align=4 (local.get $w)) (i32.const 1))
                  (then
                    (call $dump_cells0 (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))) (local.get $verbose)))
                  (else
                    (call $dump_cells (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))) (local.get $verbose)))))
              (else
                (if (local.get $verbose)
                  (then
                    (call $printf (i32.const 2691) (global.get $@stack))))))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue)))
    (if (local.get $verbose)
      (then
        (call $printf (i32.const 2689) (global.get $@stack))))
    (global.set $@stack (local.get $@stack_entry)))
  (func $dump_all (param $verbose i32)
    (local $@stack_entry i32)
    (local.set $@stack_entry (global.get $@stack))
    (if (i32.eqz (i32.load align=4 (global.get $world)))
      (then
        (call $dump_cells0 (global.get $world) (local.get $verbose)))
      (else
        (call $dump_cells (global.get $world) (local.get $verbose))))
    (call $printf (i32.const 2693) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry)))
  (func $to_arr0 (param $w i32) (param $n i32) (param $pts i32) (param $k i32)
    (local $@stack_entry i32)
    (local $y i32)
    (local $x i32)
    (local.set $@stack_entry (global.get $@stack))
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (i32.const 10)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (i32.const 10)))
            (if (i32.load8_s align=1 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.add (i32.mul (local.get $y) (i32.const 10)) (local.get $x))))
              (then
                (if (i32.ge_s (i32.load align=4 (local.get $k)) (local.get $n))
                  (then
                    (i64.store align=8 (global.get $@stack) (i64.const 490))
                    (call $printf (i32.const 2695) (global.get $@stack))
                    (unreachable)))
                (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.load align=4 (local.get $k)) (i32.const 2)) (i32.const 4))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 4))) (local.get $x)))
                (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.load align=4 (local.get $k)) (i32.const 2)) (i32.const 1)) (i32.const 4))) (i32.add (i32.load align=4 (i32.add (local.get $w) (i32.const 8))) (local.get $y)))
                (i32.store align=4 (local.get $k) (i32.add (i32.load align=4 (local.get $k)) (i32.const 1)))))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue)))
    (global.set $@stack (local.get $@stack_entry)))
  (func $to_arr1 (param $w i32) (param $n i32) (param $pts i32) (param $k i32)
    (local $y i32)
    (local $x i32)
    (block $@block_1_break
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (i32.const 5)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (i32.const 5)))
            (if (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4))))
              (then
                (if (i32.eq (i32.load align=4 (local.get $w)) (i32.const 1))
                  (then
                    (call $to_arr0 (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))) (local.get $n) (local.get $pts) (local.get $k)))
                  (else
                    (call $to_arr1 (i32.load align=4 (i32.add (i32.add (local.get $w) (i32.const 16)) (i32.mul (i32.add (i32.mul (local.get $y) (i32.const 5)) (local.get $x)) (i32.const 4)))) (local.get $n) (local.get $pts) (local.get $k))))))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue))))
  (func $to_arr (param $n i32) (param $pts i32)
    (local $@stack_entry i32)
    (local $k i32)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $k (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.const 4)) (i32.const 1)) (i32.const 8)))))
    (i32.store align=4 (local.get $k) (i32.const 0))
    (if (i32.eqz (i32.load align=4 (global.get $world)))
      (then
        (call $to_arr0 (global.get $world) (local.get $n) (local.get $pts) (local.get $k)))
      (else
        (call $to_arr1 (global.get $world) (local.get $n) (local.get $pts) (local.get $k))))
    (global.set $@stack (local.get $@stack_entry)))
  (func $mulberry32 (result f64)
    (local $t i32)
    (global.set $seed (i32.add (global.get $seed) (i32.const 1831565813)))
    (local.set $t (global.get $seed))
    (local.set $t (i32.mul (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 15))) (i32.or (local.get $t) (i32.const 1))))
    (local.set $t (i32.xor (local.get $t) (i32.add (local.get $t) (i32.mul (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 7))) (i32.or (local.get $t) (i32.const 61))))))
    (f64.div (f64.convert_i32_u (i32.xor (local.get $t) (i32.shr_u (local.get $t) (i32.const 14)))) (f64.const 4.294967296E9)))
  (func $rand_int (result i32)
    (i32.trunc_f64_s (f64.mul (f64.const 10000.0) (f64.sub (call $mulberry32) (f64.const 0.5)))))
  (func $sort_points (param $n i32) (param $pts i32)
    (local $cnt i32)
    (local $i i32)
    (local $t i32)
    (loop $@block_1_continue
      (block $@block_1_1_break
        (local.set $i (i32.const 0))
        (local.set $cnt (i32.const 0))
        (loop $@block_1_1_continue
          (br_if $@block_1_1_break (i32.ge_s (local.get $i) (i32.sub (local.get $n) (i32.const 1))))
          (if (if (result i32) (i32.lt_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4)))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 2)) (i32.const 4))))) (then (i32.const 1)) (else (i32.ne (if (result i32) (i32.ne (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4)))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 2)) (i32.const 4))))) (then (i32.const 0)) (else (i32.ne (i32.lt_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4)))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 3)) (i32.const 4))))) (i32.const 0)))) (i32.const 0))))
            (then
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br $@block_1_1_continue)))
          (local.set $t (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4)))))
          (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 2)) (i32.const 4)))))
          (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 2)) (i32.const 4))) (local.get $t))
          (local.set $t (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4)))))
          (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 3)) (i32.const 4)))))
          (i32.store align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 3)) (i32.const 4))) (local.get $t))
          (local.set $cnt (i32.add (local.get $cnt) (i32.const 1)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br $@block_1_1_continue)))
      (br_if $@block_1_continue (i32.gt_s (local.get $cnt) (i32.const 0)))))
  (func $test_1
    (local $@stack_entry i32)
    (local $i i32)
    (local $n_pts i32)
    (local $pts i32)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $n_pts (i32.const 20))
    (local.set $pts (global.get $@stack))
    (global.set $@stack (i32.add (i32.const 8) (i32.mul (i32.const 8) (i32.div_s (i32.sub (i32.add (global.get $@stack) (i32.mul (i32.mul (i32.const 2) (local.get $n_pts)) (i32.const 4))) (i32.const 1)) (i32.const 8)))))
    (block $@block_1_break
      (local.set $i (i32.const 0))
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $i) (i32.mul (i32.const 2) (local.get $n_pts))))
        (i32.store align=4 (i32.add (local.get $pts) (i32.mul (local.get $i) (i32.const 4))) (call $rand_int))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_1_continue)))
    (block $@block_2_break
      (local.set $i (i32.const 0))
      (loop $@block_2_continue
        (br_if $@block_2_break (i32.ge_s (local.get $i) (local.get $n_pts)))
        (call $set_cell (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4)))) (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4)))) (i32.const 1))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_2_continue)))
    (call $verify (global.get $world))
    (call $printf (i32.const 2733) (global.get $@stack))
    (block $@block_3_break
      (local.set $i (i32.const 0))
      (loop $@block_3_continue
        (br_if $@block_3_break (i32.ge_s (local.get $i) (local.get $n_pts)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4))))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4))))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (i32.const 2680) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_3_continue)))
    (call $sort_points (local.get $n_pts) (local.get $pts))
    (call $printf (i32.const 2745) (global.get $@stack))
    (block $@block_4_break
      (local.set $i (i32.const 0))
      (loop $@block_4_continue
        (br_if $@block_4_break (i32.ge_s (local.get $i) (local.get $n_pts)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4))))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4))))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (i32.const 2680) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_4_continue)))
    (call $to_arr (local.get $n_pts) (local.get $pts))
    (call $sort_points (local.get $n_pts) (local.get $pts))
    (call $printf (i32.const 2758) (global.get $@stack))
    (block $@block_5_break
      (local.set $i (i32.const 0))
      (loop $@block_5_continue
        (br_if $@block_5_break (i32.ge_s (local.get $i) (local.get $n_pts)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.mul (i32.const 2) (local.get $i)) (i32.const 4))))))
        (global.set $@stack (i32.add (global.get $@stack) (i32.const 8)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (i32.load align=4 (i32.add (local.get $pts) (i32.mul (i32.add (i32.mul (i32.const 2) (local.get $i)) (i32.const 1)) (i32.const 4))))))
        (global.set $@stack (i32.sub (global.get $@stack) (i32.const 8)))
        (call $printf (i32.const 2680) (global.get $@stack))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $@block_5_continue)))
    (call $printf (i32.const 2771) (global.get $@stack))
    (call $dump_all (i32.const 0))
    (global.set $@stack (local.get $@stack_entry)))
  (func $test_2
    (local $@stack_entry i32)
    (local $x i32)
    (local $y i32)
    (local $original_seed i32)
    (local $X i32)
    (local $Y i32)
    (local $density f64)
    (local.set $@stack_entry (global.get $@stack))
    (local.set $original_seed (global.get $seed))
    (local.set $density (f64.const 0.4))
    (local.set $X (i32.const 1200))
    (local.set $Y (i32.const 1600))
    (block $@block_1_break
      (local.set $y (i32.const 0))
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.ge_s (local.get $y) (local.get $Y)))
        (block $@block_1_1_break
          (local.set $x (i32.const 0))
          (loop $@block_1_1_continue
            (br_if $@block_1_1_break (i32.ge_s (local.get $x) (local.get $X)))
            (call $set_cell (local.get $x) (local.get $y) (f64.lt (call $mulberry32) (local.get $density)))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_1_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_1_continue)))
    (global.set $seed (local.get $original_seed))
    (block $@block_2_break
      (local.set $y (i32.const 0))
      (loop $@block_2_continue
        (br_if $@block_2_break (i32.ge_s (local.get $y) (local.get $Y)))
        (block $@block_2_1_break
          (local.set $x (i32.const 0))
          (loop $@block_2_1_continue
            (br_if $@block_2_1_break (i32.ge_s (local.get $x) (local.get $X)))
            (if (i32.ne (call $get_cell (local.get $x) (local.get $y)) (f64.lt (call $mulberry32) (local.get $density)))
              (then
                (i64.store align=8 (global.get $@stack) (i64.const 599))
                (call $printf (i32.const 2784) (global.get $@stack))
                (unreachable)))
            (local.set $x (i32.add (local.get $x) (i32.const 1)))
            (br $@block_2_1_continue)))
        (local.set $y (i32.add (local.get $y) (i32.const 1)))
        (br $@block_2_continue)))
    (call $printf (i32.const 2855) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry)))
  (func $main (export "main") (result i32)
    (local $@stack_entry i32)
    (local $test i32)
    (local.set $@stack_entry (global.get $@stack))
    (call $mm_init (i32.const 0) (call $__max_32s (i32.const 216) (i32.const 116)))
    (block $@block_1_break
      (local.set $test (i32.const 1))
      (loop $@block_1_continue
        (br_if $@block_1_break (i32.gt_s (local.get $test) (i32.const 2)))
        (i64.store align=8 (global.get $@stack) (i64.extend_i32_s (local.get $test)))
        (call $printf (i32.const 2859) (global.get $@stack))
        (if (i32.eq (local.get $test) (i32.const 1))
          (then
            (call $test_1))
          (else
            (call $test_2)))
        (call $verify (global.get $world))
        (if (i32.gt_s (local.get $test) (i32.const 0))
          (then
            (call $release_box (global.get $world))
            (global.set $world (i32.const 0))))
        (call $memory_stat)
        (local.set $test (i32.add (local.get $test) (i32.const 1)))
        (br $@block_1_continue)))
    (call $printf (i32.const 2584) (global.get $@stack))
    (global.set $@stack (local.get $@stack_entry))
    (i32.const 0))
  (func $__max_32s (param $a i32) (param $b i32) (result i32)
    (select (local.get $a) (local.get $b) (i32.gt_s (local.get $a) (local.get $b)))))
